cit_message_board/__init__.py
import os
from flask import Flask

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'db.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from . import db
    db.init_app(app)

    from . import auth
    auth.init_app(app)
    app.register_blueprint(auth.bp)

    from . import views
    app.register_blueprint(views.bp)

    return app

cit_message_board/auth.py
import functools

import click
from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for, abort
from werkzeug.security import check_password_hash, generate_password_hash

from .db import get_db

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()

        # If there was an error, add it to this variable
        error = None
        user = db.execute(
            'SELECT * FROM admin WHERE username = ?', (username,)
        ).fetchone()

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            # Add the login to cookies
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('views.admin'))

        flash(error)

    return render_template('login.html')

def add_admin(username, password):
    db = get_db()

    # If someone with that username already exists then return false
    try:
        db.execute(
            "INSERT INTO admin (username, password) VALUES (?, ?)",
            (username, generate_password_hash(password))
        )
        db.commit()

    except db.IntegrityError:
        return False

@bp.route('/logout')
def logout():
    # Clear the cookies
    session.clear()
    return redirect(url_for('views.index'))

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            'SELECT * FROM admin WHERE id = ?',
            (user_id,)
        ).fetchone()

def login_required(view):
    # If the user isn't logged in then send an error code
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return abort(401)

        return view(**kwargs)

    return wrapped_view

@click.command('add-admin')
@click.option('--username')
@click.option('--password')
def add_admin_command(username, password):
    """Add a new admin user."""
    if add_admin(username, password):
        click.echo('Username already exists.')
    else:
        click.echo(f'Added {username}: {password}.')

def init_app(app):
    app.cli.add_command(add_admin_command)

cit_message_board/views.py
import json
from datetime import datetime
from io import BytesIO
from flask import Blueprint, flash, g, redirect, render_template, request, url_for, send_file, jsonify
from werkzeug.exceptions import abort
import pytz

from .auth import login_required
from .db import get_db

bp = Blueprint('views', __name__)

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/admin')
@login_required
def admin():
    db = get_db()
    posts = db.execute(
        'SELECT created, begins, expires, title, author, admin_id, id FROM post'
    ).fetchall()
    return render_template('admin.html', posts=posts)

@bp.route('/add', methods=('GET', 'POST'))
def add():
    if request.method == 'POST':
        name = request.form['name']
        title = request.form['title']

        created = datetime.now().strftime('%Y-%m-%dT%H:%M')

        # Convert the time given by the user into UTC time
        deeprun_time = pytz.timezone('US/Eastern')
        utc = pytz.timezone('UTC')

        begins = deeprun_time.localize(datetime.strptime(request.form['begins'], '%Y-%m-%dT%H:%M')).astimezone(utc).strftime('%Y-%m-%dT%H:%M')
        expires = deeprun_time.localize(datetime.strptime(request.form['expires'], '%Y-%m-%dT%H:%M')).astimezone(utc).strftime('%Y-%m-%dT%H:%M')

        image = request.files['image'].read()

        db = get_db()
        db.execute(
            'INSERT INTO post (created, begins, expires, title, author, data) VALUES (?, ?, ?, ?, ?, ?)',
            (created, begins, expires, title, name, image)
        )
        db.commit()

    return render_template('add.html')

@bp.route('/live')
def live():
    return render_template('live.html')

@bp.route('/posts')
def posts():
    # Used by the front end to get a list of posts to cycle through
    db = get_db()
    # If the admin id is null it hasn't been approved
    posts = db.execute(
        'SELECT id, begins, expires FROM post WHERE NOT admin_id IS NULL'
    ).fetchall()
    filtered_posts = []
    for post in posts:
        id = post['id']
        current_time = datetime.now()
        begin_time = datetime.strptime(post['begins'], '%Y-%m-%dT%H:%M')
        expire_time = datetime.strptime(post['expires'], '%Y-%m-%dT%H:%M')
        print(begin_time)
        print(expire_time)
        if begin_time > current_time:
            continue
        elif expire_time < current_time:
            db.execute(
                'DELETE FROM post WHERE id = ?',
                (id,)
            )
            db.commit()
            continue

        filtered_posts.append(id)

    return jsonify(filtered_posts)

@bp.route('/images/<int:id>')
def images(id):
    # Used to get an image in a displayable format
    db = get_db()
    file = db.execute(
        'SELECT data FROM post WHERE id = ?',
        (id,)
    ).fetchone()['data']
    return send_file(BytesIO(file), download_name='image.png')

@bp.route('/approve/<int:id>', methods=('POST',))
@login_required
def approve(id):
    db = get_db()
    db.execute(
        'UPDATE post SET admin_id = ? WHERE id = ?',
        (g.user['id'], id)
    )
    db.commit()

    return redirect(url_for('views.admin'))

@bp.route('/delete/<int:id>', methods=('POST',))
@login_required
def delete(id):
    db = get_db()
    db.execute(
        'DELETE FROM post WHERE id = ?',
        (id,)
    )
    db.commit()

    return redirect(url_for('views.admin'))

cit_message_board/templates/add.html
{% extends 'page.html' %}

{% block header %}{% block title %}Add a message{% endblock %}{% endblock %}

{% block section %}
<form enctype="multipart/form-data" method="post">
    <label for="name">Name</label>
    <input name="name" id="name" required>
    <br>
    <label for="title">Title</label>
    <input name="title" id="title" required>
    <br>
    <label for="image">Image</label>
    <input type="file" name="image" id="image" required>
    <br>
    <label for="begins">Begins</label>
    <input type="datetime-local" name="begins" id="begins" required>
    <br>
    <label for="expires">Expires</label>
    <input type="datetime-local" name="expires" id="expires" required>
    <br>
    <input type="submit" value="Submit">
</form>
{% endblock %}

cit_message_board/templates/admin.html
{% extends 'page.html' %}

{% block header %}{% block title %}Admin Dashboard{% endblock %}{% endblock %}

{% block section %}
{% for post in posts %}
<div>
    Title: {{ post['title'] }}
    <br>
    Author: {{ post['author'] }}
    <br>
    Created: {{ post['created'] }}
    <br>
    Begins: {{ post['begins'] }}
    <br>
    Expires: {{ post['expires'] }}
    <form action="{{ url_for('views.delete', id=post['id']) }}" method="post">
        <input type="submit" value="Delete">
    </form>
    {% if post['admin_id'] == None %}
    <form action="{{ url_for('views.approve', id=post['id']) }}" method="post">
        <input type="submit" value="Approve">
    </form>
    {% endif %}
    <br>
    <img style="width: auto; height: 25vh;" src="{{ url_for('views.images', id=post['id']) }}">
</div>
{% endfor %}
{% endblock %}

cit_message_board/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %} - CIT Message Board</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>

cit_message_board/templates/index.html
{% extends 'page.html' %}

{% block header %}{% block title %}Home{% endblock %}{% endblock %}

{% block section %}
Welcome to the CIT Message Board
{% endblock %}

cit_message_board/templates/live.html
<body style="margin: 0; padding: 0; width: 100vw; height: 100vh; display: flex; justify-content: center; align-items: center; background-color: black; overflow: hidden;">
    <img style="width: 100vw; height: 100vh; object-fit: contain;" id="image">
</body>

<script>
    let posts = [];
    let index = 0;

    const getJSON = async (url) => {
        const response = await fetch(url);
        if (!response.ok)
            throw new Error(response.statusText);

        const data = response.json();
        return data;
    }

    const next = async () => {
        console.log("Fetching data...");
        await getJSON("{{ url_for('views.posts') }}").then(data => {
            console.log(data);
            posts = data
        }).catch(error => {
            console.error(error);
        });

        index++;
        if (index > posts.length - 1) {
            index = 0;
        }
        document.getElementById("image").setAttribute("src", "/images/" + posts[index]);
    }

    next();
    setInterval(next, 5000);
</script>

cit_message_board/templates/login.html
{% extends 'page.html' %}

{% block header %}{% block title %}Admin Log In{% endblock %}{% endblock %}

{% block section %}
<form method="post">
    <label for="username">Username</label>
    <input name="username" id="username" required>
    <br>
    <label for="password">Password</label>
    <input name="password" id="username" required>
    <br>
    <input type="submit" value="Log In">
</form>
{% endblock %}

cit_message_board/templates/page.html
{% extends 'base.html' %}

{% block content %}
<nav>
    <h1>CIT Message Board</h1>
    <ul>
    {% if g.user %}
        <li><span>Logged in as {{ g.user['username'] }}</span></li>
        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
        <li><a href="{{ url_for('views.admin') }}">Admin</a></li>
    {% else %}
        <li><a href="{{ url_for('auth.login') }}">Admin Login</a></li>
    {% endif %}
        <li><a href="{{ url_for('views.live') }}">Live View</a></li>
        <li><a href="{{ url_for('views.add') }}">Add</a></li>
    </ul>
</nav>
<header><h1>{% block header %}{% endblock %}</h1></header>
{% for message in get_flashed_messages() %}
    <div>{{ message }}</div>
{% endfor %}
{% block section %}{% endblock %}
{% endblock %}